export const mockData = [
  {
    text: "(电流声)",
    start: 6.88,
    end: 7.98,
    type: "audio_event",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: " ",
    start: 7.98,
    end: 8.119,
    type: "spacing",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "千",
    start: 8.119,
    end: 8.44,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "问",
    start: 8.44,
    end: 8.68,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "。",
    start: 8.68,
    end: 10.98,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "(叹气声)",
    start: 11.06,
    end: 11.85,
    type: "audio_event",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: " ",
    start: 11.85,
    end: 11.86,
    type: "spacing",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "就",
    start: 11.86,
    end: 11.98,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "在",
    start: 11.98,
    end: 12.22,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "昨",
    start: 12.22,
    end: 12.7,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "天",
    start: 12.7,
    end: 12.84,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "哈",
    start: 12.84,
    end: 13.02,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "，",
    start: 13.02,
    end: 13.459,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "千",
    start: 13.46,
    end: 13.8,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "问",
    start: 13.8,
    end: 13.9,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: " ",
    start: 13.9,
    end: 13.96,
    type: "spacing",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "Image",
    start: 13.96,
    end: 14.46,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: " ",
    start: 14.46,
    end: 14.58,
    type: "spacing",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "的",
    start: 14.58,
    end: 14.78,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "这",
    start: 14.78,
    end: 14.98,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "个",
    start: 14.98,
    end: 15.18,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "图",
    start: 15.18,
    end: 15.34,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "像",
    start: 15.34,
    end: 15.74,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "编",
    start: 15.74,
    end: 15.9,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "辑",
    start: 15.9,
    end: 16.079,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "模",
    start: 16.079,
    end: 16.4,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "型",
    start: 16.4,
    end: 16.86,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "差",
    start: 16.86,
    end: 17.12,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "一",
    start: 17.12,
    end: 17.46,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "点",
    start: 17.46,
    end: 17.62,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "儿",
    start: 17.62,
    end: 17.76,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "就",
    start: 17.76,
    end: 18.06,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "变",
    start: 18.06,
    end: 18.34,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "成",
    start: 18.34,
    end: 18.419,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "了",
    start: 18.42,
    end: 18.56,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "一",
    start: 18.56,
    end: 18.74,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "个",
    start: 18.74,
    end: 19.44,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "照",
    start: 19.44,
    end: 19.78,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "片",
    start: 19.78,
    end: 20.04,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "模",
    start: 20.04,
    end: 20.36,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "型",
    start: 20.36,
    end: 20.52,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "啊",
    start: 20.58,
    end: 20.72,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "。",
    start: 20.72,
    end: 21.34,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "骗",
    start: 21.34,
    end: 21.54,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "子",
    start: 21.54,
    end: 21.66,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "的",
    start: 21.66,
    end: 21.86,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "骗",
    start: 21.86,
    end: 23.52,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "啊",
    start: 23.52,
    end: 25.7,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "。",
    start: 25.7,
    end: 27.88,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "就",
    start: 27.88,
    end: 28.14,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "在",
    start: 28.14,
    end: 28.28,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "昨",
    start: 28.28,
    end: 28.64,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "天",
    start: 28.64,
    end: 28.84,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
  {
    text: "啊",
    start: 28.84,
    end: 28.86,
    type: "word",
    speaker_id: null,
    logprob: 0.0,
    characters: null,
  },
];
